### PR TITLE
Fixed using client commands while on a dedicated server

### PR DESCRIPTION
**Pull request by Brycey92**

### CODE REVIEW

**Comment by GirafiStudios** [comment]
I can't reproduce this <.<
Give me an example on how to reproduce it and I will look into fixing it ^^

**Comment by Brycey92** [comment]
I just coded a quick /openurl command for my own mod, which opens a specified url in a web browser, and only works on clients. I use it in MineMenu to open links to various wikis and forums.

**Comment by GirafiStudios** [comment]
Ahh okay :)
Sure, that would be great!

**Comment by Brycey92** [comment]
Here's the source file for the command: [https://gist.github.com/Brycey92/6c0b45aea53d6913f5b6](url)

**Comment by GirafiStudios** [comment]
https://github.com/dmillerw/MineMenu/commit/ef6f40fc7d7a8dae2c89896a0186a3c8a65759f5

**Pull request closed without merging**
